---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: false
  vars:
    molecule_pip_dependencies:
      - kubernetes
  tasks:

    - name: Store user ENVs
      ansible.builtin.set_fact:
        molecule_user_home_dir: "{{ lookup('ansible.builtin.env', 'HOME') }}"
        molecule_user_path: "{{ lookup('ansible.builtin.env', 'PATH') }}"

    - name: Create local bin directory
      ansible.builtin.file:
        path: "{{ molecule_user_home_dir }}/bin"
        state: directory
        mode: 0770
    
    - name: Download oc binary from OCP downloads svc endpoint
      ansible.builtin.get_url:
        url: http://downloads.openshift-console.svc.cluster.local/amd64/linux/oc
        dest: "{{ molecule_user_home_dir }}/bin/oc"
        mode: '0770'
    
    - name: Add another bin dir to system-wide $PATH.
      ansible.builtin.lineinfile:
        path: "{{ molecule_user_home_dir }}/.bashrc"
        line: 'PATH=$PATH:{{ molecule_user_home_dir }}/bin'
        state: present

    - name: Ensure python dependencies are installed
      ansible.builtin.pip:
        name: "{{ molecule_pip_dependencies }}"
        state: present
      when: molecule_pip_dependencies is defined

    - name: Install ansible-galaxy collections
      ansible.builtin.command: ansible-galaxy collection install -r /projects/rhel-edge-management-role/collections/requirements.yml

    - name: Install ansible-galaxy roles
      ansible.builtin.command: ansible-galaxy role install -r /projects/rhel-edge-management-role/roles/requirements.yml

    - name: Create directory for ansible roles
      ansible.builtin.file:
        path: /home/runner/.ansible/roles
        state: directory
        mode: 0770

    - name: Create symbolic link for rhel-edge-management-role
      ansible.builtin.file:
        src: /projects/rhel-edge-management-role
        dest: /home/runner/.ansible/roles
        state: link


# ansible-galaxy collection install -r collections/requirements.yml
# ansible-galaxy role install -r roles/requirements.yml
# mkdir -p /home/runner/.ansible/roles
# ln -s /projects/rhel-edge-management-role /home/runner/.ansible/roles